language: java
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn clean deploy -DskipTests=true
  --settings etc/settings.xml || mvn clean verify -DskipTests=true --settings etc/settings.xml'
env:
  global:
  - secure: KyyJIWSec2cLvZnl+ftdMrygv/RSPbOqDEQM9KQ8+ekHuJdH3FE5ZK1KAVflaLDe2BpyxsxQ4DC7nDMkZtUynAXdglZtV1Ayk4I/bzbAF0axNoCRfxbTfRKpCBNz1jEGnM2qb09gOaRanoHnsXezkn8RbRzOQiKQu9A+3nDXMKY=
  - secure: FVVh/JkeLYN8Bo17EIuPXNtUu1YsWG8u0qr6my/PcsfGtXv8VZdPbY5h68Dc2nQOI7UW7CO3o8AakfocWpZafhWwhTJbI/FN7Dl1JByZ/3ltRNUB22ImgTbE0uRGKUSBrrhaFZLqWKnCTJjJALuNlhR+FI4XYXfViZmUfLq/FX8=
